@startuml

[*] --> WaitForDrinkAndPayment: New Order

WaitForDrinkAndPayment -->  AwaitForPayment : Drink Ready
WaitForDrinkAndPayment -->  AwaitForDrink : Payment Received

AwaitForPayment --> [*] : Payment Received
AwaitForDrink --> [*] : Drink Ready


@enduml
