@startuml

@startuml
[*] --> WaitForDrinkAndPayment

state WaitForDrinkAndPayment {
  [*] -> AwaitingForDrink
  AwaitingForDrink --> DrinkReady : Drink Ready
  ||
  [*] -> AwaitForPayment
  AwaitForPayment --> PaymentComplete : Payment Received
}

WaitForDrinkAndPayment --> [*]

@enduml


@enduml
